### ISSUE TITLE
Request: Add R.A.T.S. compatibility to "Vault-Tec - Handy things for your vault!" Pipboy

### ISSUE THREAD

**Issue by malice936** [keyz182/R.A.T.S.#2]
Think the title says most of it, not sure how difficult it would be. Preferrably if "Vault-Tec - Handy things for your vault!" is installed add it, but I can understand if it needs an entire patch.

**Comment by keyz182** [comment]
I'll take a look, might be a few days until I have some free time though

**Comment by keyz182** [comment]
Done!

**Comment by malice936** [comment]
Thanks!
